<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'MakeCommercePrefix\\Twig\\' => array($vendorDir . '/twig/twig/src'),
    'MakeCommercePrefix\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'MakeCommercePrefix\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'MakeCommercePrefix\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'MakeCommercePrefix\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'MakeCommercePrefix\\MakeCommerceShipping\\SDK\\' => array($vendorDir . '/maksekeskus/php-shipping-sdk/src/MakeCommerce'),
    'MakeCommercePrefix\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'MakeCommercePrefix\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'MakeCommercePrefix\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
